//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
        }
        [ScaffoldColumn(false)]
        public int id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El título es requerido"), MaxLength(150)]
        [Display(Name = "Título")]
        public string titulo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha de lanzamiento")]
        public Nullable<System.DateTime> fecha_publi { get; set; }
        public string formato { get; set; }
        [DataType(DataType.Text)]
        [Range(0, 1000, ErrorMessage = "Ingresa un número valido")]
        [Display(Name = "Duración")]
        public Nullable<int> duracion { get; set; }

        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
